@echo off
REM Kayo to O11V4 Script Generator - Setup Installer
REM For Windows 7, 8, 10, 11
REM This installer requires NO administrator rights

setlocal enabledelayedexpansion

cls
echo ========================================================
echo.
echo      Kayo to O11V4 Script Generator - Setup
echo.
echo ========================================================
echo.

REM Colors and formatting
color 0A
cls

echo.
echo    Welcome to Kayo Script Generator Setup
echo    =====================================
echo.
echo    This installer will:
echo    1. Copy files to your computer
echo    2. Create a Start Menu shortcut
echo    3. Create a Desktop shortcut
echo    4. Set up the application
echo.
echo    Your Kayo credentials are NEVER stored.
echo    All files are installed locally on your PC.
echo.
pause

REM Determine install directory - default to AppData\Local
set "INSTALL_DIR=%LOCALAPPDATA%\Kayo Script Gen"

echo.
echo    Installation directory: %INSTALL_DIR%
echo.

REM Create installation directory
if not exist "%INSTALL_DIR%" (
    mkdir "%INSTALL_DIR%"
    if !errorlevel! neq 0 (
        echo.
        echo    ERROR: Could not create installation directory
        echo    Please check write permissions to: %LOCALAPPDATA%
        echo.
        pause
        exit /b 1
    )
)

echo    [1/4] Creating directories...
mkdir "%INSTALL_DIR%" 2>nul
mkdir "%INSTALL_DIR%\templates" 2>nul
mkdir "%INSTALL_DIR%\config" 2>nul
timeout /t 1 /nobreak >nul

echo    [2/4] Copying application files...
if exist "dist\KayoScriptGen.exe" (
    copy "dist\KayoScriptGen.exe" "%INSTALL_DIR%\" /Y >nul
    echo         ✓ Application executable
) else (
    echo    ERROR: KayoScriptGen.exe not found in dist\ directory
    pause
    exit /b 1
)

if exist "templates\*" (
    copy "templates\*" "%INSTALL_DIR%\templates\" /Y >nul
    echo         ✓ Web interface templates
)

if exist "config\*" (
    copy "config\*" "%INSTALL_DIR%\config\" /Y >nul
    echo         ✓ Configuration files
)

timeout /t 1 /nobreak >nul

echo    [3/4] Creating shortcuts...

REM Create Start Menu folder
if exist "%APPDATA%\Microsoft\Windows\Start Menu\Programs" (
    set "START_MENU=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Kayo Script Gen"
    if not exist "!START_MENU!" mkdir "!START_MENU!"
    
    REM Create shortcut using VBScript
    call :CreateShortcut "!START_MENU!\Kayo Script Gen.lnk" "%INSTALL_DIR%\KayoScriptGen.exe"
    echo         ✓ Start Menu shortcut created
)

REM Create Desktop shortcut
call :CreateShortcut "%USERPROFILE%\Desktop\Kayo Script Gen.lnk" "%INSTALL_DIR%\KayoScriptGen.exe"
echo         ✓ Desktop shortcut created

timeout /t 1 /nobreak >nul

echo    [4/4] Finalizing installation...

REM Save install info for uninstaller
(
    echo @echo off
    echo REM Uninstaller for Kayo Script Gen
    echo REM Do not edit this file
    echo.
    echo set "INSTALL_DIR=%INSTALL_DIR%"
    echo.
    echo echo.
    echo echo    Uninstalling Kayo Script Gen...
    echo echo.
    echo rmdir /s /q "!INSTALL_DIR!" 2>nul
    echo del "%%USERPROFILE%%\Desktop\Kayo Script Gen.lnk" 2>nul
    echo del "%%APPDATA%%\Microsoft\Windows\Start Menu\Programs\Kayo Script Gen\*" 2>nul
    echo rmdir /s /q "%%APPDATA%%\Microsoft\Windows\Start Menu\Programs\Kayo Script Gen" 2>nul
    echo.
    echo echo    Uninstall complete!
    echo echo.
    echo pause
) > "%INSTALL_DIR%\Uninstall.bat"

echo         ✓ Uninstaller created

timeout /t 1 /nobreak >nul

echo.
echo ========================================================
echo.
echo    ✓ Installation Complete!
echo.
echo ========================================================
echo.
echo    Quick Start:
echo    1. Find "Kayo Script Gen" in your Start Menu
echo       OR double-click the Desktop shortcut
echo    2. Enter your Kayo email and password
echo    3. Click "Test Credentials" to verify
echo    4. Generate your O11V4 provider script
echo    5. Download and deploy to O11V4
echo.
echo    Documentation:
echo    See QUICK_DEPLOUMENT_GUIDE.txt for help
echo.
echo    Support:
echo    For issues, see BUILD_INSTRUCTIONS.md
echo.
echo ========================================================
echo.
pause
exit /b 0

REM ===== SUBROUTINE: Create Shortcut =====
:CreateShortcut
setlocal
set "SHORTCUT=%~1"
set "TARGET=%~2"

REM Create VBScript to create shortcut
set "VBSCRIPT=%TEMP%\createlink.vbs"
(
    echo Set oWS = WScript.CreateObject("WScript.Shell"^)
    echo sLinkFile = "%SHORTCUT%"
    echo Set oLink = oWS.CreateShortcut(sLinkFile^)
    echo oLink.TargetPath = "%TARGET%"
    echo oLink.WorkingDirectory = "%INSTALL_DIR%"
    echo oLink.Description = "Generate O11V4 provider scripts with real Kayo integration"
    echo oLink.Save
) > "!VBSCRIPT!"

cscript.exe "!VBSCRIPT!" 2>nul
del "!VBSCRIPT!" 2>nul

endlocal
exit /b 0
